create table if not exists public.holdings (
  id bigint generated by default as identity primary key,
  ticker text not null unique,
  name text not null,
  amount double precision not null check (amount >= 0),
  price double precision not null check (price >= 0),
  change_percent double precision not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  ticker text not null references public.holdings(ticker),
  type text not null check (type in ('buy', 'sell')),
  amount double precision not null check (amount > 0),
  price double precision not null check (price >= 0),
  traded_at timestamptz not null default now()
);

create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  ticker text not null unique,
  name text not null,
  price double precision not null check (price >= 0),
  created_at timestamptz not null default now()
);

alter table public.holdings enable row level security;
alter table public.transactions enable row level security;
alter table public.watchlist enable row level security;

insert into public.holdings (ticker, name, amount, price, change_percent) values
  ('BTC', 'Bitcoin', 0.842, 61204, 2.14),
  ('ETH', 'Ethereum', 6.15, 3412, 12.4),
  ('SOL', 'Solana', 142, 148.2, -3.02),
  ('DOGE', 'Dogecoin', 18420, 0.184, -1.15),
  ('ADA', 'Cardano', 2140, 0.61, 5.8),
  ('LTC', 'Litecoin', 9.4, 92.1, -0.6),
  ('MATIC', 'Polygon', 3020, 0.72, 1.9)
on conflict (ticker) do nothing;

insert into public.watchlist (ticker, name, price) values
  ('DOT', 'Polkadot', 6.42),
  ('LINK', 'Chainlink', 14.9),
  ('AVAX', 'Avalanche', 28.05)
on conflict (ticker) do nothing;

insert into public.transactions (ticker, type, amount, price, traded_at)
select 'ETH', 'buy', 1.2, 3398.2, '2026-08-13 16:02:00+00'
where not exists (select 1 from public.transactions where ticker = 'ETH' and type = 'buy' and amount = 1.2);
insert into public.transactions (ticker, type, amount, price, traded_at)
select 'SOL', 'sell', 40, 148.2, '2026-08-12 11:20:00+00'
where not exists (select 1 from public.transactions where ticker = 'SOL' and type = 'sell' and amount = 40);
insert into public.transactions (ticker, type, amount, price, traded_at)
select 'BTC', 'buy', 0.05, 61204, '2026-08-10 09:15:00+00'
where not exists (select 1 from public.transactions where ticker = 'BTC' and type = 'buy' and amount = 0.05);
insert into public.transactions (ticker, type, amount, price, traded_at)
select 'DOGE', 'sell', 2000, 0.184, '2026-08-08 18:47:00+00'
where not exists (select 1 from public.transactions where ticker = 'DOGE' and type = 'sell' and amount = 2000);